# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8582bcb1d993de81af6b15ff403a0e3ec4146ae057749b11a8ab0f5919248c02773054d4e608b8806bac8cabb632d222187321d30b09ae94fcdff3e56e743aee

test:
  secret_key_base: e9094afdc10c6346ebbb7268e5f4bb51ee465b6061d0471a84d13f42730b5a71af6019641f8439c48fbe0daae172da5f62417dcd3c547a1a7eb5681097197a4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
